import type { Metadata } from "next";
import {PT_Serif} from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const serif = PT_Serif({subsets:["latin"], weight: ["400", "700"]})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${serif.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
