import type { Metadata } from "next";
import {PT_Serif, PT_Sans, PT_Mono} from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Dictionary App",
  description: "Generated by create next app",
};

const serif = PT_Serif({ subsets: ["latin"], weight: ["400", "700"] })

const sans = PT_Sans({ subsets: ["latin"], weight: ["400", "700"] });

const mono = PT_Mono({subsets: ["latin"], weight: ["400"]})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-transparent`}
      >
        {children}
      </body>
    </html>
  );
}
